linux-system-roles/metrics

README.md

- replace "Role name" by the actual role name
- do not say "Example of setting the variables" when the example shows only one variable
- remove quotes around a short string
- replace "local system" and "target host" by "managed host"
- true/false -> yes/no

minor fixes for README

---

.travis/runcollection.sh
.travis/utils.sh
tox.ini

- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.

RHELPLAN-56582 - sync collections related changes from template to metrics role

---

meta/main.yml

Signed-off-by: Jakub Haruda <jharuda@redhat.com>

meta/main.yml: CI add support for Fedora 33

---

README.md

Related https://github.com/linux-system-roles/metrics/issues/25

Document the ports used for various metrics role configurations

---

roles/performancecopilot_metrics_bpftrace/tasks/main.yml
roles/performancecopilot_metrics_bpftrace/vars/main.yml
roles/performancecopilot_metrics_elasticsearch/tasks/main.yml
roles/performancecopilot_metrics_elasticsearch/vars/main.yml
roles/performancecopilot_metrics_mssql/tasks/main.yml
roles/performancecopilot_metrics_mssql/vars/main.yml

Make sure config dir of PMDAs exist

---

roles/performancecopilot_metrics_bpftrace/tasks/main.yml
roles/performancecopilot_metrics_elasticsearch/tasks/main.yml
roles/performancecopilot_metrics_mssql/tasks/main.yml

Fix for issue #33 and issue #34.

Fixed wrong main role name in sub-roles

---

roles/performancecopilot_metrics_elasticsearch/tasks/main.yml

Proposed fix of issue https://github.com/linux-system-roles/metrics/issues/38

Make sure elasticsearch_agent is always defined

---

roles/elasticsearch/tasks/main.yml
roles/elasticsearch/vars/Fedora.yml
roles/elasticsearch/vars/main.yml

Define Fedora specific variables for export into Elasticsearch

---

roles/bpftrace/vars/CentOS_7.yml
roles/bpftrace/vars/CentOS_8.yml
roles/bpftrace/vars/RedHat_7.yml
roles/bpftrace/vars/RedHat_8.yml
roles/elasticsearch/vars/CentOS_6.yml
roles/elasticsearch/vars/CentOS_7.yml
roles/elasticsearch/vars/CentOS_8.yml
roles/elasticsearch/vars/RedHat_6.yml
roles/elasticsearch/vars/RedHat_7.yml
roles/elasticsearch/vars/RedHat_8.yml
roles/mssql/vars/CentOS_6.yml
roles/mssql/vars/CentOS_7.yml
roles/mssql/vars/CentOS_8.yml
roles/mssql/vars/RedHat_6.yml
roles/mssql/vars/RedHat_7.yml
roles/mssql/vars/RedHat_8.yml

Resolves https://github.com/linux-system-roles/metrics/issues/61
Resolves https://github.com/linux-system-roles/metrics/issues/63

Update configuration file paths to support older PCP versions

---

roles/elasticsearch/tasks/main.yml

Resolves https://github.com/linux-system-roles/metrics/issues/65

Document the reasons for the use of ignore_errors

---

.ansible-lint
.yamllint.yml
roles/bpftrace/tasks/main.yml
roles/elasticsearch/tasks/main.yml
roles/grafana/tasks/main.yml
roles/mssql/tasks/main.yml
roles/pcp/tasks/main.yml
roles/pcp/tasks/pmcd.yml
roles/redis/tasks/main.yml
tasks/main.yml
tests/check_bpftrace.yml
tests/check_default_datasources.yml
tests/check_from_elasticsearch.yml
tests/check_into_elasticsearch.yml
tests/check_retention.yml
tests/check_sasl.yml
tests/restore_services_state.yml
tests/tests_bz1855539.yml
tests/tests_bz1855544.yml
tests/tests_sanity_auth.yml

- Cleaning up yamllint line-length errors
- Cleaning up ansible-lint errors

Fix issues found by linters - enable all tests on all repos - remove suppressions

---

roles/pcp/tasks/pmlogger.yml

More info: https://bugzilla.redhat.com/show_bug.cgi?id=1967335
Please verify that this is the correct way to fix this.  It appeared to fix it in my environment.

__pcp_target_hosts not defined so loop doesn't run

---

roles/bpftrace/tasks/main.yml

bpftrace: follow bpftrace.conf symlink for latest PCP versions

---

.ansible-lint
.github/workflows/tox.yml

support python 39, ansible-core 2.12, ansible-plugin-scan

support python 39, ansible-core 2.12, ansible-plugin-scan

---

tests/check_bpftrace.yml
tests/check_from_elasticsearch.yml
tests/check_grafanapcp.yml
tests/check_header.yml
tests/check_into_elasticsearch.yml
tests/check_mssql.yml
tests/check_pmlogger.yml
tests/check_pmproxy.yml
tests/tests_bz1855539.yml

Files to be checked:
- /var/lib/pcp/pmdas/bpftrace/bpftrace.conf
- /var/lib/pcp/pmdas/elasticsearch/elasticsearch.conf
- /etc/grafana/grafana.ini
- /usr/lib/systemd/system/pcp2elasticsearch.service
- /var/lib/pcp/pmdas/mssql/mssql.conf
- /etc/sysconfig/pmlogger
- /etc/sysconfig/pmlogger_timers
- /etc/sysconfig/pmproxy
- /etc/pcp/pmie/control.d/<host>

Add test cases for the ansible_managed header.

---

README.md
tasks/main.yml
tests/check_postfix.yml
tests/tests_sanity_postfix.yml

Add a metrics_from_postfix boolean flag for the metrics role

---

tests/check_mssql.yml

Looks like a cut&paste error from some time in distant past.

Use correct role variable locations in mssql tests

---

README.md

docs: make minimum redis and grafana versions more clear

---

CHANGELOG.md

[1.8.1] - 2023-01-20
--------------------
- none
- fix pimeconf rule filesys vfs_rules support
- ansible-lint 6.x fixes (#133)
- Add check for non-inclusive language
- Avoid non-inclusive language

Version 1.8.1 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.8.3

docs(changelog): version 1.8.3 [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.8.4

docs(changelog): version 1.8.4 [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.8.5

docs(changelog): version 1.8.5 [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.8.6

docs(changelog): version 1.8.6 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.8.7
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.8.7 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.10.1

docs(changelog): version 1.10.1 [citest skip]

---

.github/workflows/ansible-lint.yml
.github/workflows/markdownlint.yml

Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

ci: make markdownlint ignore tests/roles

---

CHANGELOG.md

Update changelog and .README.html for version 1.10.2
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.10.2 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.10.3

docs(changelog): version 1.10.3 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.10.4

docs(changelog): version 1.10.4 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.10.6

docs(changelog): version 1.10.6 [citest skip]

---

CHANGELOG.md

docs: fix missing h2 markdown element

---

CHANGELOG.md

Update changelog and .README.html for version 1.10.9

docs(changelog): version 1.10.9 [citest skip]
