linux-system-roles/metrics

tests/tests_custom.yml, tests/tests_graph.yml, tests/tests_query.yml
the `when` clause was causing the role to be skipped.  It should
be removed to enable running the tests.
=> enable tests for query and metrics

vars/CentOS-6.yml, vars/RedHat-6.yml
A package with documentation is unlikely to be required for running a service.
=> Remove pcp-doc from packages

.ansible-lint, .github/workflows/tox.yml, molecule/default/molecule.yml
Deprecate the use of molecule for linting.  Use tox for ansible-lint.
The next step will be to remove the ansible-lint dependency from
the molecule environments.
=> use tox for ansible-lint instead of molecule

README.md
`metrics_with_elasticsearch` should be renamed to `metrics_into_elasticsearch`
=> Fixed a typo in README file

tests/check_into_elasticsearch.yml, tests/tests_sanity_from_elasticsearch.yml, tests/tests_sanity_into_elasticsearch.yml
Fix of misspelled Elasticsearch name as commented in https://github.com/linux-system-roles/metrics/pull/59#pullrequestreview-581550920
=> Fix of misspelled "Elasticsearch"

tests/tests_sanity_mssql.yml
pcp-pmda-mssql (and SQL Server itself) are x86_64-only.
=> Update mssql test to exclude non-x86_64 architectures

.github/workflows/tox.yml, .sanity-ansible-ignore-2.10.txt, .sanity-ansible-ignore-2.9.txt
- Add .sanity-ansible-ignore-2.{9,10}.txt to skip ansible-test symlinks test.
- Use tox-lsr 2.3.0 and enable ansible-test
- Upgrade to tox-lsr 2.3.0 which fixes several issues with running
ansible-test sanity from tox.
- Add ansible-test to the python 3.6 test list.
=> RHELPLAN-68122 - Collections - Metrics - fixing ansible-test errors

.sanity-ansible-ignore-2.10.txt, .sanity-ansible-ignore-2.9.txt
This reverts "Add .sanity-ansible-ignore-2.{9,10}.txt to skip ansible-test
symlinks test" part of commit edbc854ae7c795764051da907314903127668251.
To make ansible-test pass, instead of ignoring the symlinks in tests/roles
using the ignore file .sanity-ansible-ignore-#.#.txt, make the collection
conversion tool lsr_role2collection.py clean the symlinks up [0]. With
the change, we can get rid of .sanity-ansible-ignore-#.#.txt.
[0] - https://github.com/linux-system-roles/auto-maintenance/pull/54
=> Partial Revert "RHELPLAN-68122 - Collections - Metrics - fixing ansible-test errors"

roles/spark/vars/RedHat_9.yml
Commit 10ac5c7b introduced this when it should not have.
=> Revert accidental inclusion of var path from the spark role

CHANGELOG.md
[1.7.3] - 2022-07-19
--------------------
- none
- docs: make minimum redis and grafana versions more clear
Tackles Red Hat BZ #2094483
- restart pmie, pmlogger if changed, do not wait for handler
- make min_ansible_version a string in meta/main.yml
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add changelog_to_tag.yml to .github/workflows
- Add CHANGELOG.md
=> Version 1.7.3 - CHANGELOG.md [citest skip]

README.md, defaults/main.yml, meta/collection-requirements.yml, tasks/firewall.yml, tasks/main.yml, tasks/selinux.yml, tests/check_firewall_selinux.yml, tests/tests_sanity_auth.yml, tests/tests_sanity_basic.yml, tests/tests_sanity_bpftrace.yml, tests/tests_sanity_fullstack.yml, tests/tests_sanity_graph.yml, tests/tests_sanity_mssql.yml, tests/tests_sanity_postfix.yml, tests/tests_sanity_query.yml, tests/tests_sanity_retention.yml
- Introduce metrics_manage_firewall to use the firewall role to
manage the pmcd port, the pmproxy ports, the grafana port and
the redis port depending upon the configuration parameters.
metrics_manage_firewall is set to true, by default.
- Introduce metrics_manage_selinux to use the selinux role to
manage the pmcd port, the pmproxy ports, the grafana port and
the redis port depending upon the configuration parameters.
If the variable is set to false, the selinux configuration is
disabled.
- Add the test check task check_firewall_selinux.yml for verify
the ports status.
- Add meta/collection-requirements.yml
=> Use the firewall role and the selinux role from the metrics role

.ansible-lint
add the pcp roles to mock_roles so that ansible-lint won't complain
about them being missing
=> ci: add pcp roles to mock roles for ansible-lint

.ansible-lint, contributing.md
Provide a single, consistent contributing.md for all roles.  This mostly links to
and summarizes https://linux-system-roles.github.io/contribute.html
Allow for a role specific section which typically has information about
role particulars, role debugging tips, etc.
See https://github.com/linux-system-roles/.github/pull/19
=> docs: Consistent contributing.md for all roles - allow role specific contributing.md section

.ansible-lint
ha_cluster - add to python_roles
metrics - fix ansible-lint
=> ci: update metrics ansible-lint; add ha_cluster to python_roles

tests/tests_bz1855539.yml
I guess ansible-core 2.15 does not export `vars` defined
in a `roles` keyword in a play to other task sections in
the play.  The fix is to declare the variable in the `vars`
at the `play` level.
=> fix: make role work on ansible-core 2.15

tests/check_pmie_webhook.yml, tests/tests_verify_mssql.yml, tests/tests_verify_pmie_webhook.yml, tests/tests_verify_postfix.yml, vendor/github.com/performancecopilot/ansible-pcp/docs/pcp/setup.yml, vendor/github.com/performancecopilot/ansible-pcp/galaxy.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/bpftrace/tasks/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/elasticsearch/tasks/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/grafana/tasks/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/mssql/tasks/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/README.md, vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/defaults/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/tasks/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/tasks/pmie.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/vars/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/postfix/tasks/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/redis/tasks/main.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/repository/README.md, vendor/github.com/performancecopilot/ansible-pcp/roles/repository/templates/artifactory.debs.j2, vendor/github.com/performancecopilot/ansible-pcp/roles/repository/templates/artifactory.rpms.j2, vendor/github.com/performancecopilot/ansible-pcp/roles/repository/templates/packagecloud.debs.j2, vendor/github.com/performancecopilot/ansible-pcp/roles/repository/templates/packagecloud.rpms.j2, vendor/github.com/performancecopilot/ansible-pcp/roles/repository/vars/Debian.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/repository/vars/RedHat.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/spark/tasks/main.yml
6cbb8cc Bump version to 2.3.0 for latest changes
35389e7 feat: support for ostree systems
630e87e fix: add missing pmie webhook action configuration functionality
e50979a fix: switch the repository role over to using Packagecloud
git-subtree-dir: vendor/github.com/performancecopilot/ansible-pcp
git-subtree-split: 6cbb8cc0accebed05985390e677ac1a760294803
=> feat: sync with latest ansible-pcp

.ansible-lint, .ostree/get_ostree_data.sh, .ostree/packages-runtime-CentOS-9.txt, .ostree/packages-testing-CentOS-9.txt, meta/collection-requirements.yml, tasks/main.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
=> refactor: improve support for ostree systems

README.md, defaults/main.yml, tasks/main.yml, tests/check_notification.yml, tests/handle_test_failure.yml, tests/restore_services_state.yml, tests/tests_bz1855539.yml, tests/tests_bz1855544.yml, tests/tests_default.yml, tests/tests_verify_auth.yml, tests/tests_verify_basic.yml, tests/tests_verify_bpftrace.yml, tests/tests_verify_from_elasticsearch.yml, tests/tests_verify_fullstack.yml, tests/tests_verify_graph.yml, tests/tests_verify_into_elasticsearch.yml, tests/tests_verify_mssql.yml, tests/tests_verify_notification.yml, tests/tests_verify_pmie_webhook.yml, tests/tests_verify_postfix.yml, tests/tests_verify_query.yml, tests/tests_verify_retention.yml
Resolves Red Hat issue RHEL-13760
=> fix: add missing pmie webhook action configuration functionality

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.10.0
=> docs(changelog): version 1.10.0 [citest skip]

.github/workflows/ansible-lint.yml, .github/workflows/ansible-managed-var-comment.yml, .github/workflows/ansible-plugin-scan.yml, .github/workflows/ansible-test.yml, .yamllint.yml, tests/tests_verify_postfix.yml
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
=> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

.ostree/packages-testing-CentOS-10.txt, .ostree/packages-testing-RedHat-10.txt, meta/main.yml
According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …
=> fix: add support for EL10

tests/restore_services_state.yml
If the test enabled the firewall, stop it during cleanup.
=> test: stop firewall if used by test

.ansible-lint, .ostree/packages-runtime-CentOS-10.txt, .ostree/packages-runtime-RedHat-10.txt, .ostree/packages-testing-CentOS-10.txt, .ostree/packages-testing-Fedora.txt, .ostree/packages-testing-RedHat-10.txt, CHANGELOG.md, README.md, defaults/main.yml, meta/main.yml, tasks/firewall.yml, tasks/main.yml, tests/check_default_datasources.yml, tests/check_firewall_selinux.yml, tests/check_keyserver.yml, tests/check_redis.yml, tests/restore_services_state.yml, tests/roles/keyserver, tests/roles/redis, tests/tests_verify_fullstack.yml, tests/tests_verify_query.yml, vendor/github.com/performancecopilot/ansible-pcp/.github/workflows/pr-title-lint.yml, vendor/github.com/performancecopilot/ansible-pcp/roles/keyserver/templates/redis_5.conf.j2, vendor/github.com/performancecopilot/ansible-pcp/roles/keyserver/templates/redis_6.conf.j2, vendor/github.com/performancecopilot/ansible-pcp/roles/keyserver/templates/valkey_7.conf.j2
Enhancement: Support Valkey as an alternative to Redis
Reason: Redis is no longer open source and is being removed from distributions
Result: PCP scalable query language + Grafana support continue to function
Issue Tracker Tickets (Jira or BZ if any): RHEL-29939
=> fix: add support for Valkey

.github/workflows/pr-title-lint.yml, .github/workflows/subtree.yml, .github/workflows/woke.yml
Seems to resolve a github actions lint-style warning.
=> fix: add leading triple-hyphen to all github workflow files

tasks/firewall.yml, tests/check_firewall_selinux.yml
Cause: The role was using incorrect syntax for specifying the
keyserver port for the firewall.
Consequence: The role would give an error when configuring
the keyserver port in the firewall.
Fix: Use the correct syntax in the role and in the test
used to check the firewall.
Result: The role can configure the firewall port for the
keyserver correctly.
=> fix: Use correct syntax for keyserver port and test check
